# 1. SCOPE & DOMAIN LIMITS
# These prevent the AI from acting as something it is not (e.g., a doctor or lawyer).
FORBIDDEN_TOPICS = [
    "medical advice", "diagnosis", "prescription",
    "legal litigation", "court representation", 
    "financial investment", "stock trading", "crypto advice",
    "politics", "religious debate",
    "baking", "cooking", "gaming cheats"
]

# 2. ETHICAL & BIAS CATEGORIES
# Used to ensure the AI doesn't give biased career advice based on protected traits.
SENSITIVE_ATTRIBUTES = [
    "gender", "race", "ethnicity", "religion", 
    "disability", "age", "sexual orientation"
]

# 3. OPERATIONAL GUARDRAILS
# Mechanical rules for the system's behavior.
MAX_RECOMMENDATIONS = 3  # Based on the RAG top_k setting
MIN_CONFIDENCE_SCORE = 0.4  # Minimum RAG score to be considered 'reliable'

# 4. MANDATORY MESSAGES & DISCLAIMERS
# These ensure the user knows they are talking to an AI.
SAFETY_MESSAGES = {
    "ai_disclaimer": (
        "\n\n[NOTICE: This analysis is generated by CareerPilot AI. "
        "Suggestions are based on available database documents and should be "
        "verified with a professional career counselor.]"
    ),
    "failure_msg": (
        "I'm sorry, but your request involves topics outside my professional scope "
        "as a Career Mentor. I am only designed to assist with CV analysis, "
        "job matching, and interview preparation."
    ),
    "hallucination_warning": (
        "Note: Some suggestions could not be fully verified against our database. "
        "Please proceed with caution."
    )
}

# 5. LANGUAGE QUALITY
# Ensures the output stays professional and academic.
BANNED_PHRASES = [
    "I guarantee", "100% success", "You will definitely get", 
    "Trust me", "I promise"
]